### ISSUE TITLE
calclex.py example produces NameError

### ISSUE THREAD

**Issue by joedougherty** [dabeaz/sly#7]
The calclex.py example from the "Writing a Lexer" section of https://github.com/dabeaz/sly/blob/master/docs/sly.rst raises a NameError when run. Console output to demonstrate:

```
$ (master) python3 --version
Python 3.6.5

$ (master) cat calclex.py 
# calclex.py

from sly import Lexer

class CalcLexer(Lexer):
    # Set of token names.   This is always required
    tokens = { ID, NUMBER, PLUS, MINUS, TIMES,
               DIVIDE, ASSIGN, LPAREN, RPAREN }

    # String containing ignored characters between tokens
    ignore = ' \t'

    # Regular expression rules for tokens
    ID      = r'[a-zA-Z_][a-zA-Z0-9_]*'
    NUMBER  = r'\d+'
    PLUS    = r'\+'
    MINUS   = r'-'
    TIMES   = r'\*'
    DIVIDE  = r'/'
    ASSIGN  = r'='
    LPAREN  = r'\('
    RPAREN  = r'\)'


if __name__ == '__main__':
    data = 'x = 3 + 42 * (s - t)'
    lexer = CalcLexer()
    for tok in lexer.tokenize(data):
        print('type=%r, value=%r' % (tok.type, tok.value))

$ (master) python3 calclex.py 
Traceback (most recent call last):
  File "calclex.py", line 5, in <module>
    class CalcLexer(Lexer):
  File "calclex.py", line 7, in CalcLexer
    tokens = { ID, NUMBER, PLUS, MINUS, TIMES,
NameError: name 'ID' is not defined
```
I am running sly v0.3. I take it I must be doing something wrong, but I do not see what.

**Comment by dabeaz** [comment]
I suspect that this is being run in an older version of SLY such as SLY-0.2 from pypi.  It works (by design) on current github version of SLY.

**Comment by joedougherty** [comment]
@dabeaz Right you are. Looks like I was unknowingly running a previous version. Thanks!
